# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e8c6f7f27e4a21f27acecd2eb3529176b61723bbd841380385415b7d250e4988ee97fbdcd40ba7057ce5fa3072cbb08238e8cc038259ad2f0248da9512f4c3e

test:
  secret_key_base: 21ac1611b5748c41051efef6b85c4523786f842281612953385720f15948215538341688d67c59c5a14ede0351f5cdea8e39c4f30d6d3e12a21ebe53b7b5e8af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
